export const IMAGEPATH = {
    SPLASH_BACKGROUND: require("../../assets/images/splash/splash.png"),
     SPLASH_LOGO: require("../../assets/images/splash/splash_logo/Logo.png"),
    CHARACHTER_ICON: require("../../assets/images/Login/Charachter/Cahrachter.png"),
    SHADOW_BACKGROUND: require("../../assets/images/Login/backgroundShadow/Shadow.png"),
    EMAIL_ICON: require("../../assets/images/Login/EmialIcon/Email.png"),
    LOCK_ICON: require("../../assets/images/Login/LOCkIcon/lock.png"),
    LOGIN_SHADOW: require("../../assets/images/Login/loginShadow/Shadow.png"),
    BORDER_COLOR: require("../../assets/images/Login/LoginBorder/border.png"),
    LOGIN_SHADOW2: require("../../assets/images/Register/RegisterBorder/ReBorder.png"),
    LOGIN_SHADOW3: require("../../assets/images/Register/PasswordBorder/password.png"),
    PHONE_ICON: require("../../assets/images/Register/cellIcon/Phone.png"),
    BACK_ICON: require("../../assets/images/Register/backIcon/back.png"),
    CODE_ICON: require("../../assets/images/Register/codeSend/code.png"),
    BGRESET_ICON: require("../../assets/images/ResetPassword/BGReset/BG.png"),
    TFBG_ICON: require("../../assets/images/ResetPassword/TFBG/TextF.png"),
    TFBG2_ICON: require("../../assets/images/ResetPassword/TBG2/Tbg2.png"),
    FEMALE_ICON: require("../../assets/images/SelectGender/FemaleHuman/FemaleIcon.png"),
    MALE_ICON: require("../../assets/images/SelectGender/MaleHuman/MaleIcon.png"),
    SELECTED_BG: require("../../assets/images/SelectGender/MaleSelector/mSelect.png"),
    NOTSELECTED_BG: require("../../assets/images/SelectGender/FemaleSelector/fSelect.png"),
    HEIGHT_BG: require("../../assets/images/SelectGender/HeightBG/Height.png"),
    UP_Arrow:require("../../assets/images/SelectGender/UpArrow/Vector.png"),
    DOWN_Arrow:require("../../assets/images/SelectGender/DownArrow/Vector.png"),
    LOCATION_BG:require("../../assets/images/LocationPage/LocationAllow/Loaction.png"),
    BUTTON_Border:require("../../assets/images/LocationPage/LocationBorder/Border.png"),
    BELL_Icon:require("../../assets/images/HomePage/BellIcon/Bell.png"),
    PROFILE_Icon:require("../../assets/images/HomePage/HumanPic/Profile.png"),
    HEADER_IMAGE:require("../../assets/images/HomePage/HomeSwipperImage/Heder.png"),
    BUTTON_ICON:require("../../assets/images/HomePage/TouchableButton/HButtonBG.png"),
    RUNNING_ICON:require("../../assets/images/HomePage/Running/Running.png"),
    WALKING_ICON:require("../../assets/images/HomePage/Walking/Walking.png"),
    CYCALLING_ICON:require("../../assets/images/HomePage/Cycalling/Cycalling.png"),
    TASKBG_ICON:require("../../assets/images/HomePage/TaskBG/TaskBg.png"),
    COLORRUN_ICON:require("../../assets/images/HomePage/ColorRunningICon/cRun.png"),
    BELL1_ICON:require("../../assets/images/Bell1/Bell1.png"),
    MEN1_ICON:require("../../assets/images/men1/men1.png"),
    PARK_ICON:require("../../assets/images/Park/park.png"),
    SQUARE_ICON:require("../../assets/images/SQUARE1/SQUARE.png"),
    RUNNING_ICON:require("../../assets/images/RUNNING/RUNNING.png"),
    CYCLING_ICON:require("../../assets/images/CYCLING/CYCLING.png"),
    WALKING_ICON:require("../../assets/images/WALKING/WALKING.png"),
    RECTANGLE1_ICON:require("../../assets/images/RECTANGLE1/RECTANGLE1.png"),
    BGGREEN_ICON:require("../../assets/images/bgGreen/bgGreen.png"),
    LONGEST_ICON:require("../../assets/images/Longest/Longest.png"),
    LOCATION_ICON:require("../../assets/images/Location1/Location1.png"),
    TAB_ICON:require("../../assets/images/Tab/Tab.png"),
    HOME_ICON:require("../../assets/images/Home/home.png"),
    HEXAGON_ICON:require("../../assets/images/Hexagonal/hexagon.png"),
    BLOCKS_ICON:require("../../assets/images/Blocks/Blocks.png"),
    //DOLLAR_ICON:require("../../assets/images/Dollar/Dollar.png"),
    BAR_ICON:require("../../assets/images/BAR/bar.png"),

}